apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: devmeet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: config
          mountPath: /etc/grafana
        - name: dashboards-prov
          mountPath: /etc/grafana/provisioning/dashboards
        - name: dashboards-json
          mountPath: /var/lib/grafana/dashboards
      volumes:
      - name: config
        configMap:
          name: grafana-config
      - name: dashboards-prov
        configMap:
          name: grafana-dashboards
          items:
            - key: dashboards.yaml
              path: dashboards.yaml
      - name: dashboards-json
        configMap:
          name: grafana-dashboards
          items:
            - key: devmeet-dashboard.json
              path: devmeet-dashboard.json
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: devmeet
spec:
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
